# -*- mode: ruby -*-
# vi: set ft=ruby :

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

unless Vagrant.has_plugin?("vagrant-vmware-desktop")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-vmware-desktop plugin is missing. Please install it using 'vagrant plugin install vagrant-vmware-desktop' and rerun 'vagrant up'"
end

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2004"

  config.vm.box_check_update = false

  # config.vm.synced_folder "~/shared", "/shared"
  config.vm.provider "vmware_desktop" do |v|

    # Customize the amount of memory on the VM:
    v.vmx["memsize"] = "122880"
    # v.vmx["memsize"] = "65536"
    # v.vmx["memsize"] = "32768"
    # v.vmx["memsize"] = "16384"
    v.vmx["numvcpus"] = 32
    # v.vmx["numvcpus"] = 16
  end
  config.disksize.size = "100GB"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  #config.vm.provision :docker
  #config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
end